import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { observeGPU, gpu } from './gpu';

test('3D metadata edits preserve the view while geometry, history and units refresh', async ({ page }) => {
  test.setTimeout(120_000);
  await observeGPU(page);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/editor');
  await page.getByRole('button', { name: 'Export', exact: true }).click();
  const chooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Import JSON', exact: true }).click();
  await (await chooser).setFiles(resolve('tests/fixtures/connected-dimensions.openplan.json'));
  await page.getByRole('button', { name: '3D', exact: true }).click();
  await page.waitForLoadState('networkidle');
  await expect.poll(async () => (await gpu(page))[0]?.draws ?? 0).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'Edit Mode', exact: true }).click();
  const canvas = page.getByRole('region', { name: '3D floor plan viewer' }).locator('canvas').last();
  const bounds = (await canvas.boundingBox())!;
  await canvas.click({ position: { x: bounds.width * 0.4, y: bounds.height * 0.6 } });
  const thickness = page.getByRole('spinbutton', { name: 'Thickness (cm)', exact: true });
  await expect(thickness).toBeVisible();
  await page.getByRole('button', { name: 'Top-Down View', exact: true }).click();
  const settle = () => page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  await settle();
  const pixels = async () => createHash('sha256').update(await canvas.evaluate((node: HTMLCanvasElement) => node.toDataURL())).digest('hex');
  const originalPixels = await pixels(), originalResources = (await gpu(page))[0].created;
  await page.getByRole('textbox', { name: 'Item notes', exact: true }).fill('Keep this top-down view');
  await page.getByRole('textbox', { name: 'Item notes', exact: true }).press('Tab');
  await settle();
  expect((await gpu(page))[0].created).toEqual(originalResources);
  expect(await pixels()).toBe(originalPixels);
  // Import name is stable and visible; editing it must not recenter the camera.
  await page.getByRole('button', { name: 'QA Connected Dimensions', exact: true }).click();
  await page.getByRole('textbox', { name: 'Project name', exact: true }).fill('3D metadata preservation');
  await page.getByRole('textbox', { name: 'Project name', exact: true }).press('Enter');
  await settle();
  expect((await gpu(page))[0].created).toEqual(originalResources);
  expect(await pixels()).toBe(originalPixels);
  await expect(page.getByRole('textbox', { name: 'Item notes', exact: true })).toHaveValue('Keep this top-down view');

  const originalThickness = await thickness.inputValue();
  await thickness.fill('35'); await thickness.press('Tab');
  await expect.poll(async () => (await gpu(page))[0].created.Buffer).toBeGreaterThan(originalResources.Buffer);
  expect(await pixels()).not.toBe(originalPixels);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(thickness).toHaveValue(originalThickness);
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(thickness).toHaveValue('35');
  await settle();
  const beforeUnits = (await gpu(page))[0].created.Texture;
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Dimensions', exact: true }).click();
  await page.getByRole('button', { name: 'ft, inch', exact: true }).click();
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: 'Thickness (in)', exact: true })).toBeVisible();
  await expect.poll(async () => (await gpu(page))[0].created.Texture).toBeGreaterThan(beforeUnits);
  expect(errors).toEqual([]);
});
